qihangerp:
  name: 启航电商ERP
  order:
    version: 2.4.21

#mybatis-plus:
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  type-aliases-package: cn.qihangerp.oms.domain;cn.qihangerp.module.domain;
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志